-- Site   : Programmers
-- Title  : 자동차 대여 기록 별 대여 금액 구하기 (LEVEL 4)
-- Link   : https://school.programmers.co.kr/learn/courses/30/lessons/151141
-- Date   : 2026-01-02 / 2026-03-21 (복습)

# SELECT * FROM CAR_RENTAL_COMPANY_CAR #대여 중인 자동차들의 회사 정보
# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY #자동차 대여 기록 정보
# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN #자동차 종류 별 대여 기간 종류

-- 자동차 종류가 '트럭'인 자동차의 대여 기록
# SELECT CAR_ID, CAR_TYPE, DAILY_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = '트럭'

-- 결과는 대여금액(FEE), 대여기록ID, 대여금액리스트
-- 대여 금액 내림차순, 대여 기록 ID 내림차순 정렬

-- 대여 기간 할인율을 JOIN해서 어떻게 날짜와 일치시키는가?
# SELECT CAR_TYPE, DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN

-- DURATION_TYPE을 숫자로 바꿔야 한다.
# SELECT CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) AS TYPE
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN

# -- CAR_TYPE으로 JOIN 
# -- 답은 더블 조인 
# SELECT H.HISTORY_ID, C.DAILY_FEE FEE
# FROM CAR_RENTAL_COMPANY_CAR C
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
# JOIN (SELECT 
#       CAR_TYPE,
#       CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) AS DURATION,
#       DISCOUNT_RATE
#       FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) P ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_TYPE = '트럭'
#     AND DATEDIFF(END_DATE, START_DATE) + 1 = P.DURATION
# GROUP BY H.HISTORY_ID
# ORDER BY HISTORY_ID DESC, FEE DESC;

# ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE  # 30일 이상 * 할인율을 적용한 총 대여금

SELECT
    H.HISTORY_ID, -- 대여기간에 따른 할인율
    ROUND( # (1)기존 금액 x (2)대여기간 x (3)할인율
        C.DAILY_FEE # (1)
        * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) # (2)
        * CASE # (3)
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN (100 - 10) / 100.0
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN (100 - 7) / 100.0
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN (100 - 5) / 100.0
            ELSE 1.0
        END
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
  ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;

