-- Site   : Programmers
-- Title  : 그룹별 조건에 맞는 식당 목록 출력하기 (LEVEL 4)
-- Link   : https://school.programmers.co.kr/learn/courses/30/lessons/131124
-- Date   : 2026-03-03


# SELECT 
#     MP.MEMBER_NAME,
#     RR.REVIEW_TEXT,
#     DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
# FROM MEMBER_PROFILE MP
# JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
# GROUP BY MP.MEMBER_ID
# ORDER BY REVIEW_DATE, REVIEW_TEXT;

# SELECT
#     MP.MEMBER_NAME,
#     COUNT(*)
# FROM MEMBER_PROFILE MP
# JOIN (

# ) MR ON MP.MEMBER_ID = MR.MEMBER_ID
# GROUP BY MP.MEMBER_NAME

WITH TOP_MEMBER AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (SELECT MAX(CNT ) FROM (SELECT COUNT(*) CNT FROM REST_REVIEW GROUP BY MEMBER_ID) t)
    )
SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
JOIN TOP_MEMBER TM ON RR.MEMBER_ID = TM.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;

-- CTE는 이렇게 구분이 필요할 때 사용
-- 늦잠
