-- Site   : Programmers
-- Title  : 5월 식품들의 총매출 조회하기 (LEVEL 4)
-- Link   : https://school.programmers.co.kr/learn/courses/30/lessons/131117
-- Date   : 2026-03-06 / 2026-03-13

# SELECT 
#     FO.PRODUCT_ID,
#     FP.PRODUCT_NAME,
#     SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
# FROM(
#     SELECT *
#     FROM FOOD_ORDER
#     WHERE PRODUCE_DATE >= '2022-05-01'
#     AND PRODUCE_DATE <  '2022-06-01'
# JOIN FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
# GROUP BY FO.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID ASC;

-- 문제풀이

# SELECT
#     FP.PRODUCT_ID,
#     FP.PRODUCT_NAME,
#     FO.AMOUNT TOTAL_SALES
# FROM FOOD_PRODUCT FP
# JOIN (
#     SELECT
#         PRODUCT_ID,
#         PRODUCE_DATE,
#         SUM(AMOUNT) AMOUNT
#     FROM FOOD_ORDER
#     WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
#     GROUP BY PRODUCT_ID
# ) FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
# ORDER BY AMOUNT DESC, PRODUCT_ID;

-- 총매출은 가격 * 수량
-- ORDER BY FP.PRODUCT_ID 명시적 테이블 이름 사용
-- 정석: 2022년 5월 생산분만 필터링하고, 제품별 총매출(가격*수량) 구한 다음 정렬

SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE >= '2022-05-01'
  AND FO.PRODUCE_DATE <  '2022-06-01'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;

-- SELECT에 집계함수가 아닌 컬럼을 쓰려면, 같이 GROUP BY
-- DATE_FORAMT은 데이터 전체를 포맷해서 비교하기 떄문에 ANT 조건연산자료 범위 비교가 효율이 좋음